# Dockerfile.build
FROM python:3.13-slim

WORKDIR /app

# Встановлюємо залежності
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копіюємо проект
COPY . .

# Тестовий запуск
CMD ["python", "svitlo_monitor.py"]
